name: CI-blog-app

on:
  push:
    branches:
      - main
    paths:
      - 'apps/blog/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

      - name: create dotenv
        run: |
          touch ./apps/blog/.env
          echo "NOTION_KEY=${{ secrets.NOTION_KEY }}" >> ./apps/blog/.env

      - name: Setup credentials to access private repositories
        run: |
          git config --global user.email "yjj0287@gmail.com"
          git config --global user.name "Yeonju Jo"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}

      - name: Deploy web-app
        working-directory: apps/blog
        run: |
          YARN_IGNORE_NODE=1 yarn deploy
